"""ST-OMR training laboratory package."""

from .core import (
    ChordEvent,
    DisplayAccidental,
    NoteEvent,
    NotationIntent,
    Pitch,
    RationalDuration,
    RestEvent,
)
from .validator import (
    ValidationIssue,
    ValidationResult,
    validate_chord_event,
    validate_note_event,
    validate_rest_event,
    validate_v1_event,
)
from .structure import Clef, Measure, Part, Score, TimeSignature, Voice
from .structure_validator import (
    validate_measure,
    validate_part,
    validate_score,
    validate_time_signature,
    validate_voice,
)
from .generator import (
    DEFAULT_GENERATOR_VERSION,
    DEFAULT_SCHEMA_VERSION,
    GenerationValidationError,
    GeneratorConfig,
    config_fingerprint,
    generate_score,
)
from .musicxml_writer import (
    MUSICXML_PART_ID,
    MUSICXML_PART_NAME,
    MUSICXML_VERSION,
    MUSICXML_WRITER_VERSION,
    MusicXMLWriteError,
    compute_musicxml_divisions,
    musicxml_sha256,
    write_musicxml,
)
from .musicxml_validator import (
    MAX_MUSICXML_BYTES,
    MUSICXML_SCHEMA_SOURCE_BLOBS,
    MUSICXML_SCHEMA_SOURCE_COMMIT,
    MUSICXML_SCHEMA_SHA256,
    validate_musicxml,
    validate_musicxml_semantics,
    validate_musicxml_xsd,
    verify_musicxml_schema_assets,
)
from .musicxml_roundtrip import (
    SemanticEventProjection,
    SemanticMeasureProjection,
    SemanticPartProjection,
    SemanticPitchProjection,
    SemanticScoreProjection,
    SemanticVoiceProjection,
    SupportedV1RoundTripError,
    compare_semantic_projections,
    parse_supported_v1_musicxml_projection,
    project_score_semantics,
    verify_supported_v1_round_trip,
)

__all__ = [
    "ChordEvent",
    "DisplayAccidental",
    "NoteEvent",
    "NotationIntent",
    "Pitch",
    "RationalDuration",
    "RestEvent",
    "ValidationIssue",
    "ValidationResult",
    "validate_chord_event",
    "validate_note_event",
    "validate_rest_event",
    "validate_v1_event",
    "Clef",
    "Measure",
    "Part",
    "Score",
    "TimeSignature",
    "Voice",
    "validate_measure",
    "validate_part",
    "validate_score",
    "validate_time_signature",
    "validate_voice",
    "DEFAULT_GENERATOR_VERSION",
    "DEFAULT_SCHEMA_VERSION",
    "GenerationValidationError",
    "GeneratorConfig",
    "config_fingerprint",
    "generate_score",
    "MUSICXML_PART_ID",
    "MUSICXML_PART_NAME",
    "MUSICXML_VERSION",
    "MUSICXML_WRITER_VERSION",
    "MusicXMLWriteError",
    "compute_musicxml_divisions",
    "musicxml_sha256",
    "write_musicxml",
    "MAX_MUSICXML_BYTES",
    "MUSICXML_SCHEMA_SOURCE_BLOBS",
    "MUSICXML_SCHEMA_SOURCE_COMMIT",
    "MUSICXML_SCHEMA_SHA256",
    "validate_musicxml",
    "validate_musicxml_semantics",
    "validate_musicxml_xsd",
    "verify_musicxml_schema_assets",
    "SemanticEventProjection",
    "SemanticMeasureProjection",
    "SemanticPartProjection",
    "SemanticPitchProjection",
    "SemanticScoreProjection",
    "SemanticVoiceProjection",
    "SupportedV1RoundTripError",
    "compare_semantic_projections",
    "parse_supported_v1_musicxml_projection",
    "project_score_semantics",
    "verify_supported_v1_round_trip",
]
