"""Frozen Stage 7-D4 specialist-OMR architecture contract.

This module is declarative only. It defines the V1 specialist task graph,
ground-truth provenance classes, graphical-geometry policy, split boundaries,
deterministic fusion rules, and deferred musical surface. It contains no model,
optimizer, trainer, dataloader, checkpoint loader, or TEST evaluation path.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from hashlib import sha256
import json
import re
from typing import Final


STAGE7D4_ARCHITECTURE_VERSION: Final[str] = "stage7d4-specialist-omr-architecture-v1"
STAGE7D4_CONTRACT_SCHEMA: Final[str] = "stage7d4-specialist-architecture-contract-v1"
_HEX64_RE = re.compile(r"^[0-9a-f]{64}$")

# Ground truth is never generated by a learned model. Synthetic spatial labels
# must come from pinned renderer/transform lineage; real spatial labels require
# independent human-verified annotation.
GT_CANONICAL_MUSIC: Final[str] = "canonical_music"
GT_RENDERER_GEOMETRY: Final[str] = "pinned_renderer_geometry"
GT_DETERMINISTIC_TRANSFORM: Final[str] = "deterministic_geometry_transform"
GT_HUMAN_VERIFIED_ANNOTATION: Final[str] = "human_verified_annotation"
GT_ADMITTED_REAL_MUSICXML: Final[str] = "admitted_real_musicxml"

ALLOWED_GT_SOURCES: Final[tuple[str, ...]] = (
    GT_CANONICAL_MUSIC,
    GT_RENDERER_GEOMETRY,
    GT_DETERMINISTIC_TRANSFORM,
    GT_HUMAN_VERIFIED_ANNOTATION,
    GT_ADMITTED_REAL_MUSICXML,
)


@dataclass(frozen=True, slots=True)
class SpecialistDatasetContract:
    """One independently auditable specialist ground-truth set."""

    set_name: str
    task_id: str
    labels: tuple[str, ...]
    synthetic_ground_truth: tuple[str, ...]
    real_ground_truth: tuple[str, ...]
    geometry_required: bool

    def __post_init__(self) -> None:
        if not self.set_name.endswith("Set"):
            raise ValueError("specialist dataset names must end in 'Set'")
        if not self.task_id or not self.task_id.isascii():
            raise ValueError("task_id must be non-empty ASCII")
        if not self.labels or len(set(self.labels)) != len(self.labels):
            raise ValueError("labels must be non-empty and unique")
        if not self.synthetic_ground_truth or not self.real_ground_truth:
            raise ValueError("both synthetic and real ground-truth policies are required")
        for source in self.synthetic_ground_truth + self.real_ground_truth:
            if source not in ALLOWED_GT_SOURCES:
                raise ValueError(f"unsupported ground-truth source: {source}")
        if self.geometry_required:
            synthetic = set(self.synthetic_ground_truth)
            if GT_RENDERER_GEOMETRY not in synthetic or GT_DETERMINISTIC_TRANSFORM not in synthetic:
                raise ValueError(
                    "synthetic geometry labels require renderer geometry and deterministic transform lineage"
                )
            if GT_HUMAN_VERIFIED_ANNOTATION not in self.real_ground_truth:
                raise ValueError("real geometry labels require human-verified annotation")


@dataclass(frozen=True, slots=True)
class SpecialistTaskContract:
    """One V1 specialist inference boundary."""

    task_id: str
    dataset_name: str
    responsibility: str
    depends_on: tuple[str, ...]
    inputs: tuple[str, ...]
    outputs: tuple[str, ...]
    trainable: bool
    confidence_required: bool

    def __post_init__(self) -> None:
        if not self.task_id or not self.task_id.isascii():
            raise ValueError("task_id must be non-empty ASCII")
        if not self.dataset_name.endswith("Set"):
            raise ValueError("dataset_name must reference a specialist set")
        if not self.responsibility:
            raise ValueError("responsibility must be non-empty")
        if len(set(self.depends_on)) != len(self.depends_on):
            raise ValueError("depends_on entries must be unique")
        if not self.inputs or not self.outputs:
            raise ValueError("specialist inputs/outputs must be non-empty")
        if len(set(self.inputs)) != len(self.inputs) or len(set(self.outputs)) != len(self.outputs):
            raise ValueError("specialist inputs/outputs must be unique")
        if self.confidence_required and "confidence" not in self.outputs:
            raise ValueError("confidence-required specialist must expose confidence")


V1_SPECIALIST_DATASETS: Final[tuple[SpecialistDatasetContract, ...]] = (
    SpecialistDatasetContract(
        set_name="StaffSet",
        task_id="staff_geometry",
        labels=(
            "staff_instance_id",
            "staff_instance_bbox",
            "five_staff_lines",
            "staff_spacing",
        ),
        synthetic_ground_truth=(GT_RENDERER_GEOMETRY, GT_DETERMINISTIC_TRANSFORM),
        real_ground_truth=(GT_HUMAN_VERIFIED_ANNOTATION,),
        geometry_required=True,
    ),
    SpecialistDatasetContract(
        set_name="StructureSet",
        task_id="structure",
        labels=(
            "system_id",
            "system_bbox",
            "measure_id",
            "measure_bbox",
            "barline_x",
            "clef_g2_bbox",
            "meter_bbox",
            "meter_class",
        ),
        synthetic_ground_truth=(GT_CANONICAL_MUSIC, GT_RENDERER_GEOMETRY, GT_DETERMINISTIC_TRANSFORM),
        real_ground_truth=(GT_HUMAN_VERIFIED_ANNOTATION, GT_ADMITTED_REAL_MUSICXML),
        geometry_required=True,
    ),
    SpecialistDatasetContract(
        set_name="NoteHeadSet",
        task_id="notehead",
        labels=("notehead_bbox", "notehead_center", "fill_class", "canonical_event_id"),
        synthetic_ground_truth=(GT_CANONICAL_MUSIC, GT_RENDERER_GEOMETRY, GT_DETERMINISTIC_TRANSFORM),
        real_ground_truth=(GT_HUMAN_VERIFIED_ANNOTATION, GT_ADMITTED_REAL_MUSICXML),
        geometry_required=True,
    ),
    SpecialistDatasetContract(
        set_name="RhythmSet",
        task_id="rhythm",
        labels=(
            "notehead_id",
            "stem_presence",
            "stem_direction",
            "beam_count",
            "flag_count",
            "duration_class",
        ),
        synthetic_ground_truth=(GT_CANONICAL_MUSIC, GT_RENDERER_GEOMETRY, GT_DETERMINISTIC_TRANSFORM),
        real_ground_truth=(GT_HUMAN_VERIFIED_ANNOTATION, GT_ADMITTED_REAL_MUSICXML),
        geometry_required=True,
    ),
    SpecialistDatasetContract(
        set_name="RestSet",
        task_id="rest",
        labels=("rest_bbox", "rest_class", "duration_class", "canonical_event_id"),
        synthetic_ground_truth=(GT_CANONICAL_MUSIC, GT_RENDERER_GEOMETRY, GT_DETERMINISTIC_TRANSFORM),
        real_ground_truth=(GT_HUMAN_VERIFIED_ANNOTATION, GT_ADMITTED_REAL_MUSICXML),
        geometry_required=True,
    ),
    SpecialistDatasetContract(
        set_name="AccidentalSet",
        task_id="accidental",
        labels=("accidental_bbox", "accidental_class", "canonical_event_id"),
        synthetic_ground_truth=(GT_CANONICAL_MUSIC, GT_RENDERER_GEOMETRY, GT_DETERMINISTIC_TRANSFORM),
        real_ground_truth=(GT_HUMAN_VERIFIED_ANNOTATION, GT_ADMITTED_REAL_MUSICXML),
        geometry_required=True,
    ),
    SpecialistDatasetContract(
        set_name="PitchSet",
        task_id="staff_position",
        labels=("notehead_id", "staff_position", "canonical_pitch_audit"),
        synthetic_ground_truth=(GT_CANONICAL_MUSIC, GT_RENDERER_GEOMETRY, GT_DETERMINISTIC_TRANSFORM),
        real_ground_truth=(GT_HUMAN_VERIFIED_ANNOTATION, GT_ADMITTED_REAL_MUSICXML),
        geometry_required=True,
    ),
    SpecialistDatasetContract(
        set_name="ChordSet",
        task_id="chord_grouping",
        labels=("notehead_id", "chord_group_id", "chord_size", "shared_onset_audit"),
        synthetic_ground_truth=(GT_CANONICAL_MUSIC, GT_RENDERER_GEOMETRY, GT_DETERMINISTIC_TRANSFORM),
        real_ground_truth=(GT_HUMAN_VERIFIED_ANNOTATION, GT_ADMITTED_REAL_MUSICXML),
        geometry_required=True,
    ),
    SpecialistDatasetContract(
        set_name="ContextSet",
        task_id="context_validation",
        labels=(
            "measure_capacity",
            "event_onsets",
            "event_durations",
            "accidental_scope",
            "chord_onsets",
            "musicxml_validity",
        ),
        synthetic_ground_truth=(GT_CANONICAL_MUSIC,),
        real_ground_truth=(GT_ADMITTED_REAL_MUSICXML,),
        geometry_required=False,
    ),
)


V1_SPECIALIST_TASKS: Final[tuple[SpecialistTaskContract, ...]] = (
    SpecialistTaskContract(
        task_id="staff_geometry",
        dataset_name="StaffSet",
        responsibility=(
            "locate every graphical occurrence of the one logical V1 staff across one or more rendered systems"
        ),
        depends_on=(),
        inputs=("grayscale_score_region",),
        outputs=("staff_instances", "confidence"),
        trainable=True,
        confidence_required=True,
    ),
    SpecialistTaskContract(
        task_id="structure",
        dataset_name="StructureSet",
        responsibility=(
            "group staff instances into systems, locate measures/barlines, classify the supported meter, and confirm G2 clef presence"
        ),
        depends_on=("staff_geometry",),
        inputs=("grayscale_score_region", "staff_geometry_candidates"),
        outputs=(
            "system_bboxes",
            "measure_bboxes",
            "barline_positions",
            "clef_g2_candidate",
            "meter_candidate",
            "confidence",
        ),
        trainable=True,
        confidence_required=True,
    ),
    SpecialistTaskContract(
        task_id="notehead",
        dataset_name="NoteHeadSet",
        responsibility="detect note-head centers/bounds and open-versus-filled appearance without assigning pitch",
        depends_on=("staff_geometry", "structure"),
        inputs=("measure_crop", "staff_geometry_candidates"),
        outputs=("notehead_candidates", "fill_class", "confidence"),
        trainable=True,
        confidence_required=True,
    ),
    SpecialistTaskContract(
        task_id="rest",
        dataset_name="RestSet",
        responsibility="detect supported V1 rest glyphs and their visual duration class",
        depends_on=("staff_geometry", "structure"),
        inputs=("measure_crop", "staff_geometry_candidates"),
        outputs=("rest_candidates", "rest_class", "duration_candidate", "confidence"),
        trainable=True,
        confidence_required=True,
    ),
    SpecialistTaskContract(
        task_id="accidental",
        dataset_name="AccidentalSet",
        responsibility="detect sharp/flat/natural glyph candidates without directly mutating sounding pitch",
        depends_on=("staff_geometry", "structure", "notehead"),
        inputs=("measure_crop", "notehead_candidates"),
        outputs=("accidental_candidates", "accidental_class", "confidence"),
        trainable=True,
        confidence_required=True,
    ),
    SpecialistTaskContract(
        task_id="rhythm",
        dataset_name="RhythmSet",
        responsibility="infer supported V1 note duration from note-head/stem/beam/flag evidence",
        depends_on=("staff_geometry", "structure", "notehead"),
        inputs=("measure_crop", "notehead_candidates"),
        outputs=(
            "notehead_id",
            "stem_presence",
            "stem_direction",
            "beam_count",
            "flag_count",
            "duration_candidate",
            "confidence",
        ),
        trainable=True,
        confidence_required=True,
    ),
    SpecialistTaskContract(
        task_id="staff_position",
        dataset_name="PitchSet",
        responsibility="estimate each note head's discrete staff position; absolute pitch is resolved deterministically later",
        depends_on=("staff_geometry", "structure", "notehead"),
        inputs=("notehead_candidates", "staff_instances"),
        outputs=("notehead_id", "staff_position", "confidence"),
        trainable=True,
        confidence_required=True,
    ),
    SpecialistTaskContract(
        task_id="chord_grouping",
        dataset_name="ChordSet",
        responsibility="group vertically aligned note heads into supported 2-4 note V1 chord candidates",
        depends_on=("structure", "notehead", "rhythm", "staff_position"),
        inputs=("notehead_candidates", "duration_candidates", "staff_positions"),
        outputs=("chord_groups", "member_notehead_ids", "confidence"),
        trainable=True,
        confidence_required=True,
    ),
    SpecialistTaskContract(
        task_id="context_validation",
        dataset_name="ContextSet",
        responsibility="deterministically fuse specialist candidates and veto musically inconsistent V1 interpretations",
        depends_on=(
            "staff_geometry",
            "structure",
            "notehead",
            "rest",
            "accidental",
            "rhythm",
            "staff_position",
            "chord_grouping",
        ),
        inputs=("all_specialist_candidates", "canonical_v1_policy"),
        outputs=("validated_candidate_music", "conflicts", "low_confidence_regions", "candidate_confidence"),
        trainable=False,
        confidence_required=False,
    ),
)


# These capabilities remain outside V1 and may not silently enter a specialist
# dataset, model head, fusion rule, validation metric, or training target.
DEFERRED_SPECIALIST_SURFACE: Final[tuple[str, ...]] = (
    "multiple_voices",
    "grand_staff",
    "multiple_instruments",
    "cross_staff",
    "tuplets",
    "ties",
    "slurs",
    "dotted_values",
    "full_measure_rests",
    "multi_measure_rests",
    "nonzero_key_signatures",
)


V1_MUSIC_POLICY: Final[dict[str, object]] = {
    "parts": 1,
    "logical_staves_per_part": 1,
    "voices": 1,
    "rendered_staff_instances_per_page": "one_or_more",
    "clef": "G2",
    "key_fifths": 0,
    "meters": ("2/4", "3/4", "4/4"),
    "note_durations": ("whole", "half", "quarter", "eighth"),
    "rest_durations": ("half", "quarter", "eighth"),
    "chord_sizes": (2, 3, 4),
    "display_accidentals": ("sharp", "flat", "natural"),
}


GEOMETRY_LABEL_POLICY: Final[dict[str, object]] = {
    "synthetic_source_space": "pinned_verovio_svg",
    "training_coordinate_space": "final_png_pixels",
    "canonical_event_link_required_where_applicable": True,
    "unlinked_or_ambiguous_renderer_element": "reject_specialist_sample",
    "clean_raster_mapping": "svg_viewbox_to_exact_cairosvg_raster_dimensions",
    "rotation_mapping": "replay_exact_pillow_rotate_expand_true_geometry",
    "photometric_transforms_change_geometry": False,
    "jpeg_roundtrip_changes_geometry": False,
    "geometry_transform_must_be_fingerprinted": True,
}


SPLIT_POLICY: Final[dict[str, object]] = {
    "family_exclusive": True,
    "specialist_sets_inherit_source_family_split": True,
    "train_families": 410,
    "validation_families": 51,
    "test_families": 51,
    "test_model_development_access": False,
    "test_specialist_dataset_derivation_during_development": False,
    "sealed_test_stage": 9,
}


FUSION_POLICY: Final[dict[str, object]] = {
    "learned_fusion": False,
    "direct_absolute_pitch_prediction_is_authoritative": False,
    "pitch_rule": "G2_clef_plus_staff_position_plus_measure_accidental_state",
    "accidental_association": "geometry_candidates_then_deterministic_scope_validation",
    "measure_duration_must_fill_exactly": True,
    "chord_size_min": 2,
    "chord_size_max": 4,
    "chord_members_share_onset": True,
    "chord_members_share_duration": True,
    "unsupported_or_ambiguous_result": "veto_or_low_confidence_candidate",
    "musicxml_writer": "deterministic_existing_writer",
    "musicxml_validation": "independent_existing_validator_and_roundtrip",
}


TRAINING_DATA_POLICY: Final[dict[str, object]] = {
    "ai_generated_ground_truth": False,
    "scoremosaic_upload_is_automatic_training_data": False,
    "teacher_correction_is_automatic_training_data": False,
    "teacher_correction_requires_explicit_admission": True,
    "real_geometry_requires_human_verified_annotation": True,
    "online_learning": False,
    "automatic_learning": False,
}


def _canonical_json_bytes(payload: object) -> bytes:
    return json.dumps(
        payload,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=True,
        allow_nan=False,
    ).encode("ascii")


def _dataset_map() -> dict[str, SpecialistDatasetContract]:
    return {item.set_name: item for item in V1_SPECIALIST_DATASETS}


def _task_map() -> dict[str, SpecialistTaskContract]:
    return {item.task_id: item for item in V1_SPECIALIST_TASKS}


def validate_stage7d4_architecture() -> None:
    """Fail closed if the frozen specialist contract is internally inconsistent."""

    datasets = _dataset_map()
    tasks = _task_map()
    if len(datasets) != len(V1_SPECIALIST_DATASETS):
        raise ValueError("specialist dataset names must be unique")
    if len(tasks) != len(V1_SPECIALIST_TASKS):
        raise ValueError("specialist task ids must be unique")
    if set(item.task_id for item in V1_SPECIALIST_DATASETS) != set(tasks):
        raise ValueError("every specialist task must have exactly one dataset contract")
    for task in V1_SPECIALIST_TASKS:
        if task.dataset_name not in datasets:
            raise ValueError(f"unknown specialist dataset: {task.dataset_name}")
        if datasets[task.dataset_name].task_id != task.task_id:
            raise ValueError("task/dataset identity mismatch")
        for dependency in task.depends_on:
            if dependency not in tasks:
                raise ValueError(f"unknown specialist dependency: {dependency}")
            if dependency == task.task_id:
                raise ValueError("specialist task cannot depend on itself")

    # Explicit DFS cycle check keeps the execution order auditable.
    visiting: set[str] = set()
    visited: set[str] = set()

    def visit(task_id: str) -> None:
        if task_id in visited:
            return
        if task_id in visiting:
            raise ValueError("specialist dependency graph contains a cycle")
        visiting.add(task_id)
        for dependency in tasks[task_id].depends_on:
            visit(dependency)
        visiting.remove(task_id)
        visited.add(task_id)

    for task_id in tasks:
        visit(task_id)

    context = tasks["context_validation"]
    if context.trainable:
        raise ValueError("V1 context fusion must remain deterministic")
    staff_position = tasks["staff_position"]
    forbidden_pitch_outputs = {"pitch", "pitch_name", "midi", "octave", "step"}
    if forbidden_pitch_outputs.intersection(staff_position.outputs):
        raise ValueError("staff-position specialist may not authoritatively predict absolute pitch")
    if "staff_position" not in staff_position.outputs:
        raise ValueError("staff-position specialist must expose discrete staff position")

    if V1_MUSIC_POLICY["logical_staves_per_part"] != 1:
        raise ValueError("V1 must remain one logical staff per part")
    if V1_MUSIC_POLICY["rendered_staff_instances_per_page"] != "one_or_more":
        raise ValueError("V1 pages must allow repeated graphical staff instances across systems")
    if GEOMETRY_LABEL_POLICY["unlinked_or_ambiguous_renderer_element"] != "reject_specialist_sample":
        raise ValueError("ambiguous synthetic renderer geometry must fail closed")
    if GEOMETRY_LABEL_POLICY["geometry_transform_must_be_fingerprinted"] is not True:
        raise ValueError("specialist geometry transforms must be fingerprinted")
    if GEOMETRY_LABEL_POLICY["photometric_transforms_change_geometry"] is not False:
        raise ValueError("photometric transforms must not rewrite spatial labels")

    if SPLIT_POLICY["test_model_development_access"] is not False:
        raise ValueError("TEST must remain sealed from model development")
    if SPLIT_POLICY["test_specialist_dataset_derivation_during_development"] is not False:
        raise ValueError("TEST specialist labels must not be derived during development")
    if TRAINING_DATA_POLICY["ai_generated_ground_truth"] is not False:
        raise ValueError("AI-generated ground truth is forbidden")
    if TRAINING_DATA_POLICY["online_learning"] is not False or TRAINING_DATA_POLICY["automatic_learning"] is not False:
        raise ValueError("online/automatic learning is forbidden")
    if TRAINING_DATA_POLICY["teacher_correction_is_automatic_training_data"] is not False:
        raise ValueError("teacher corrections cannot become automatic training data")
    if FUSION_POLICY["learned_fusion"] is not False:
        raise ValueError("Stage 7-D4 V1 fusion must remain deterministic")


def stage7d4_architecture_payload() -> dict[str, object]:
    validate_stage7d4_architecture()
    return {
        "schema": STAGE7D4_CONTRACT_SCHEMA,
        "version": STAGE7D4_ARCHITECTURE_VERSION,
        "v1_music_policy": V1_MUSIC_POLICY,
        "geometry_label_policy": GEOMETRY_LABEL_POLICY,
        "split_policy": SPLIT_POLICY,
        "training_data_policy": TRAINING_DATA_POLICY,
        "fusion_policy": FUSION_POLICY,
        "datasets": [asdict(item) for item in V1_SPECIALIST_DATASETS],
        "tasks": [asdict(item) for item in V1_SPECIALIST_TASKS],
        "deferred_surface": DEFERRED_SPECIALIST_SURFACE,
    }


def stage7d4_architecture_fingerprint() -> str:
    return sha256(_canonical_json_bytes(stage7d4_architecture_payload())).hexdigest()


def is_sha256_hex(value: object) -> bool:
    return isinstance(value, str) and _HEX64_RE.fullmatch(value) is not None
